// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0tyhKJ78BQtqg3EJOKSoDsS_V0ADFjAc',
    appId: '1:392585398177:web:c1e44458badaaf6be16de0',
    messagingSenderId: '392585398177',
    projectId: 'scissors-7a405',
    authDomain: 'scissors-7a405.firebaseapp.com',
    storageBucket: 'scissors-7a405.appspot.com',
    measurementId: 'G-FRT58YJ80P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw1Ab4c_Eo9wG_FH8vd082dtWmaehG-c8',
    appId: '1:392585398177:android:0552a159225271dfe16de0',
    messagingSenderId: '392585398177',
    projectId: 'scissors-7a405',
    storageBucket: 'scissors-7a405.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAxMWV27st-TwKE6OOWBGcBxnbdl0TKYg',
    appId: '1:392585398177:ios:0cb3fe79052b56d3e16de0',
    messagingSenderId: '392585398177',
    projectId: 'scissors-7a405',
    storageBucket: 'scissors-7a405.appspot.com',
    iosBundleId: 'com.example.salon2Booking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAxMWV27st-TwKE6OOWBGcBxnbdl0TKYg',
    appId: '1:392585398177:ios:8979343d4b70bc49e16de0',
    messagingSenderId: '392585398177',
    projectId: 'scissors-7a405',
    storageBucket: 'scissors-7a405.appspot.com',
    iosBundleId: 'com.example.salon2Booking.RunnerTests',
  );
}
